# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3090:3306  # 前面一个端口是宿主机的端口，后面一个是adminer镜像端口, adminer是一个mysql管理客户端

  adminer:
    image: adminer
    ports:
      - 8090:8080 # 前面一个端口是宿主机的端口，后面一个是adminer端口
