services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: my_postgres
    ports:
      - '5432:5432'
    volumes:
      - '/Users/zhengxiyun/Zack/codes/DB/postgresql_data:/bitnami/postgresql'
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: 123456 
      POSTGRESQL_POSTGRES_PASSWORD: 'zack123!'
      POSTGRESQL_DATABASE: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
